import type { Metadata } from 'next'
import './globals.css'
import Header from './header'

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  setIsAuthenticated,
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
      <Header
            setIsAuthenticated={setIsAuthenticated}
          />
      <main className="flex min-h-screen flex-col items-center justify-between p-24">
        {children}
      </main>
    </div>
  )
}